language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
  - go get github.com/gorilla/context
  - go get github.com/julienschmidt/httprouter
  - go get github.com/justinas/alice

script:
  - go test ./...

matrix:
  allow_failures:
    - go: tip
